/*
 * @Author: zhangyuxuan
 * @Date: 2022-07-03 17:41:42
 * @LastEditTime: 2022-07-04 17:02:51
 * @LastEditors: zhangyuxuan
 * @FilePath: \Discord-BE\entity\src\lib.rs
 */
//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

pub mod prelude;

pub mod duty;
pub mod sea_orm_active_enums;
pub mod user;

