//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "week")]
pub enum Week {
    #[sea_orm(string_value = "Fri")]
    Fri,
    #[sea_orm(string_value = "Mon")]
    Mon,
    #[sea_orm(string_value = "Sat")]
    Sat,
    #[sea_orm(string_value = "Sun")]
    Sun,
    #[sea_orm(string_value = "Thur")]
    Thur,
    #[sea_orm(string_value = "Tues")]
    Tues,
    #[sea_orm(string_value = "Wed")]
    Wed,
}
